-- RehabTrack Supabase schema
-- Run this once in Supabase Dashboard > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  daily_target integer not null default 20 check (daily_target between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.exercise_sessions (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references auth.users(id) on delete cascade,
  exercise_name text not null,
  target_reps integer not null default 20 check (target_reps > 0),
  reps integer not null default 0 check (reps >= 0),
  status text not null default 'active' check (status in ('active','completed','cancelled')),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  avg_flex double precision,
  avg_motion_angle double precision,
  performance_score integer check (performance_score between 0 and 100)
);

create table if not exists public.devices (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references auth.users(id) on delete cascade,
  device_code text not null unique,
  device_name text not null default 'ESP32 Rehab Sensor',
  enabled boolean not null default true,
  active_session_id uuid references public.exercise_sessions(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.sensor_readings (
  id bigint generated by default as identity primary key,
  patient_id uuid not null references auth.users(id) on delete cascade,
  device_id uuid not null references public.devices(id) on delete cascade,
  session_id uuid references public.exercise_sessions(id) on delete set null,
  flex_value integer not null default 0,
  bend_angle double precision not null default 0,
  accel_x double precision not null default 0,
  accel_y double precision not null default 0,
  accel_z double precision not null default 0,
  gyro_x double precision not null default 0,
  gyro_y double precision not null default 0,
  gyro_z double precision not null default 0,
  motion_angle double precision not null default 0,
  rep_detected boolean not null default false,
  quality_score integer not null default 0 check (quality_score between 0 and 100),
  created_at timestamptz not null default now()
);

create index if not exists idx_sessions_patient_started on public.exercise_sessions(patient_id, started_at desc);
create index if not exists idx_readings_patient_created on public.sensor_readings(patient_id, created_at desc);
create index if not exists idx_readings_session on public.sensor_readings(session_id);
create index if not exists idx_devices_patient on public.devices(patient_id);

-- Automatically create a patient profile after Supabase Auth signup.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', 'Patient'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Atomic rep increment called only by the server-side telemetry route.
create or replace function public.increment_session_rep(p_session_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  new_reps integer;
begin
  update public.exercise_sessions
  set reps = reps + 1
  where id = p_session_id and status = 'active'
  returning reps into new_reps;
  return new_reps;
end;
$$;

-- Only the server-side service role may call the atomic rep increment RPC.
revoke execute on function public.increment_session_rep(uuid) from public, anon, authenticated;
grant execute on function public.increment_session_rep(uuid) to service_role;

-- New Supabase projects no longer expose public tables to the Data API
-- automatically. Grant only the operations used by the patient website.
grant usage on schema public to authenticated;
grant select, update on table public.profiles to authenticated;
grant select, insert, update on table public.devices to authenticated;
grant select, insert, update on table public.exercise_sessions to authenticated;
grant select on table public.sensor_readings to authenticated;

-- Row Level Security: patients can only see/manage their own rows.
alter table public.profiles enable row level security;
alter table public.devices enable row level security;
alter table public.exercise_sessions enable row level security;
alter table public.sensor_readings enable row level security;

drop policy if exists "profile_select_own" on public.profiles;
create policy "profile_select_own" on public.profiles for select to authenticated
using ((select auth.uid()) = id);

drop policy if exists "profile_update_own" on public.profiles;
create policy "profile_update_own" on public.profiles for update to authenticated
using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "device_select_own" on public.devices;
create policy "device_select_own" on public.devices for select to authenticated
using ((select auth.uid()) = patient_id);

drop policy if exists "device_insert_own" on public.devices;
create policy "device_insert_own" on public.devices for insert to authenticated
with check ((select auth.uid()) = patient_id);

drop policy if exists "device_update_own" on public.devices;
create policy "device_update_own" on public.devices for update to authenticated
using ((select auth.uid()) = patient_id) with check ((select auth.uid()) = patient_id);

drop policy if exists "session_select_own" on public.exercise_sessions;
create policy "session_select_own" on public.exercise_sessions for select to authenticated
using ((select auth.uid()) = patient_id);

drop policy if exists "session_insert_own" on public.exercise_sessions;
create policy "session_insert_own" on public.exercise_sessions for insert to authenticated
with check ((select auth.uid()) = patient_id);

drop policy if exists "session_update_own" on public.exercise_sessions;
create policy "session_update_own" on public.exercise_sessions for update to authenticated
using ((select auth.uid()) = patient_id) with check ((select auth.uid()) = patient_id);

drop policy if exists "reading_select_own" on public.sensor_readings;
create policy "reading_select_own" on public.sensor_readings for select to authenticated
using ((select auth.uid()) = patient_id);

-- Enable Postgres Changes for the two tables used by the live dashboard.
-- This block is safe to run more than once.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'sensor_readings'
  ) then
    alter publication supabase_realtime add table public.sensor_readings;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'exercise_sessions'
  ) then
    alter publication supabase_realtime add table public.exercise_sessions;
  end if;
end;
$$;
